file-upload:
  client-path: /file
  server-path: /Users/sakkda/Documents/Fileuploads/
  base-uri: http://localhost:${server.port}${file-upload.client-path}

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 100MB
  application:
    name: e-commerce-api

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9091/realms/codequest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9432/db_ecommerce
    username: ecommerce_v2
    password: qwer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9090

keycloak:
  server-url: http://localhost:9091
  client-id: user-from-spring
  client-secret: 5IEblziACyyy9ZJFj0eyCpsEGV6pFx5W8RgLDVvRqPAXxHrGGe0B9o5wzjuNjpQWwtyy5lXsYKZEIl5qNYAQFe
  realm: ecommerce