file-upload:
  client-path: /file
  server-path: /Users/sakkda/Documents/Fileuploads/
  base-uri: http://localhost:${server.port}${file-upload.client-path}

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 100MB
  application:
    name: e-commerce-api

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/codequest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/e_commerce_v2
    username: postgres
    password: qwer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9090

keycloak:
  server-url: http://localhost:8080
  client-id: spring
  client-secret: QSQC3AM2qQsdMAPrvJ44DIrFTV9zNHFo
  realm: codequest