file-upload:
  server-path: /Users/sakkda/Documents/Fileuploads/

spring:
  application:
    name: e-commerce-api

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/hacker

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/e_commerce_v2
    username: postgres
    password: qwer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9090